import type { CodegenState } from '../types.js';
import { camelCase, getAttributes } from '../utils.js';

export function generateDs(state: CodegenState): string {
  const { dsName, tableName, schemaName, columns, moduleCode, index } = state;
  const schemaPart =
    schemaName && schemaName !== 'public' && schemaName !== 'default'
      ? `\n  schema: '${schemaName}',`
      : '';

  const attributes = getAttributes(columns, index);

  return `/* Generated by uv-core codegen */

import type { TableDataSource } from 'uv-core';
import { DefaultAttribute, DefaultDataSource, DefaultFullAccess } from 'uv-core';
import type { ${dsName} } from '../../../common/ds/types/${moduleCode ? `${moduleCode}/` : ''}${dsName}.js';

export const ${dsName}DS: TableDataSource<${dsName}> = {
  ...DefaultDataSource,
  id: '${dsName}',${schemaPart}
  tableName: '${tableName}',
  attributes: [${attributes}
  ],
  access: [
    {
      ...DefaultFullAccess,
      roleCode: 'admin',
    },
    {
      ...DefaultFullAccess,
      roleCode: 'all_users',
    },
  ],
};
`;
}
