/* Generated by uv-core codegen */

import type { CodegenState } from '../types.js';
import { camelCase, startCase } from '../utils.js';

export function generatePage(state: CodegenState): string {
  const typeName = state.dsName; // E.g. Customer
  const fields = state.columns;
  const primaryCol = fields.find((c) => c.primary) || fields[0];
  const primaryCode = camelCase(primaryCol.name);

  // Generate Table Columns Headers and Cells
  const headersHtml = fields
    .map((col) => `<th className="px-6 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">${startCase(col.name)}</th>`)
    .join('\n                    ');

  const cellsHtml = fields
    .map((col) => {
      const code = camelCase(col.name);
      if (col.type === 'boolean') {
        return `<td className="px-6 py-4 whitespace-nowrap text-sm text-slate-300">
                      {row.${code} ? 'Yes' : 'No'}
                    </td>`;
      }
      return `<td className="px-6 py-4 whitespace-nowrap text-sm text-slate-300">
                      {String(row.${code} ?? '')}
                    </td>`;
    })
    .join('\n                    ');

  const tableWithForms = state.template === 'page-layout';
  const hasSearch = state.template === 'page-layout' || state.template === 'table-with-search';

  const storeHookImport = `import { use${typeName}Store } from '../../lib/client/hooks/use${typeName}Store.js';`;
  const formComponentImport = tableWithForms ? `import { ${typeName}Form } from '../../components/${typeName}Form.js';` : '';

  return `/* Generated by uv-core codegen */

'use client';

import * as React from 'react';
import { useState } from 'react';
${storeHookImport}
${formComponentImport}

export default function ${typeName}Page() {
  const store = use${typeName}Store();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedRowId, setSelectedRowId] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);

  const handleAddNew = () => {
    const newId = store.createNew();
    setSelectedRowId(newId);
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await store.save();
      setSelectedRowId(null);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (confirm('Are you sure you want to delete this record?')) {
      store.deleteRow(id);
      await store.save();
      if (selectedRowId === id) {
        setSelectedRowId(null);
      }
    }
  };

  const rows = store.list();
  
  // Filter rows based on search term
  const filteredRows = rows.filter((row) => {
    if (!searchTerm) return true;
    const term = searchTerm.toLowerCase();
    return Object.values(row).some((val) => 
      String(val).toLowerCase().includes(term)
    );
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex justify-between items-center border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl font-semibold text-slate-100">${startCase(state.tableName)} Management</h1>
          <p className="text-sm text-slate-400">View, create, and manage records in the ${state.tableName} table</p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => store.refresh()}
            className="px-4 py-2 text-sm font-medium bg-slate-800 text-slate-200 border border-slate-700 rounded-md hover:bg-slate-700 transition"
          >
            Refresh
          </button>
          {${tableWithForms} && (
            <button
              onClick={handleAddNew}
              className="px-4 py-2 text-sm font-medium bg-indigo-600 text-white rounded-md hover:bg-indigo-500 transition"
            >
              Add New
            </button>
          )}
          {store.isStoreDirty() && (
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="px-4 py-2 text-sm font-medium bg-emerald-600 text-white rounded-md hover:bg-emerald-500 transition disabled:opacity-50"
            >
              {isSaving ? 'Saving...' : 'Save Changes'}
            </button>
          )}
        </div>
      </div>

      {${hasSearch} && (
        <div className="flex items-center gap-3 bg-slate-900/40 p-4 rounded-lg border border-slate-800">
          <svg className="h-5 w-5 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            type="text"
            placeholder="Search records..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1 bg-transparent border-0 text-sm text-slate-200 focus:outline-none focus:ring-0 placeholder-slate-500"
          />
        </div>
      )}

      <div className="grid grid-cols-1 ${tableWithForms ? 'lg:grid-cols-3' : ''} gap-6">
        <div className="${tableWithForms ? 'lg:col-span-2' : ''} bg-slate-900/30 rounded-lg border border-slate-800 overflow-hidden">
          {store.isBusy() && filteredRows.length === 0 ? (
            <div className="p-8 text-center text-sm text-slate-400">Loading data...</div>
          ) : filteredRows.length === 0 ? (
            <div className="p-8 text-center text-sm text-slate-400">No records found.</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-800">
                <thead className="bg-slate-900/50">
                  <tr>
                    ${headersHtml}
                    <th className="px-6 py-3 text-right text-xs font-semibold text-slate-400 uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {filteredRows.map((row) => {
                    const rowId = String(row._id || row.${primaryCode} || '');
                    const isSelected = selectedRowId === rowId;
                    return (
                      <tr
                        key={rowId}
                        onClick={() => ${tableWithForms} && setSelectedRowId(rowId)}
                        className={\`cursor-pointer transition hover:bg-slate-800/40 \${isSelected ? 'bg-slate-800/60' : ''}\`}
                      >
                        ${cellsHtml}
                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDelete(rowId);
                            }}
                            className="text-red-400 hover:text-red-300 font-medium"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {${tableWithForms} && selectedRowId && (
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-lg font-medium text-slate-200">Editor</h2>
              <button
                onClick={() => setSelectedRowId(null)}
                className="text-xs text-slate-400 hover:text-slate-300"
              >
                Close Editor
              </button>
            </div>
            <${typeName}Form store={store} rowId={selectedRowId} />
          </div>
        )}
      </div>
    </div>
  );
}
`;
}
