import type { CodegenState } from '../types.js';
import { kebabCase } from '../utils.js';

export function generateStore(state: CodegenState): string {
  const { dsName, moduleCode, template } = state;
  const alias = kebabCase(dsName);

  return `/* Generated by uv-core codegen */

'use client';

import type { ${dsName} } from '@/lib/common/ds/types/${moduleCode ? `${moduleCode}/` : ''}${dsName}.js';
import { useStore } from 'uv-core/client';

export function use${dsName}Store() {
  return useStore<${dsName}>({
    datasourceId: '${dsName}',
    page: '${alias}-page',
    alias: '${alias}-all',
    limit: 20,
    includeCount: true,${template === 'simple' ? '' : '\n    autoQuery: true,'}
    // onInitialized: async (store) => {
    //   store.setIsLoading(false);
    // },
  });
}
`;
}
