/* Generated by uv-core codegen */

import type { CodegenState } from '../types.js';

export function generateStore(state: CodegenState): string {
  const typeName = state.dsName; // E.g., Customer
  return `/* Generated by uv-core codegen */

'use client';

import { useStore as useBaseStore } from 'uv-core/client';
import type { StoreClass, StoreProps } from 'uv-core/client';
import type { ${typeName} } from '../../common/ds/types/${typeName}.js';

export function use${typeName}Store(props?: Omit<StoreProps<${typeName}>, 'datasourceId'>) {
  return useBaseStore<${typeName}>({
    datasourceId: '${state.dsName}',
    ...props,
  });
}

export type ${typeName}Store = StoreClass<${typeName}>;
`;
}
