/* Generated by uv-core codegen */

import type { CodegenState } from '../types.js';
import { camelCase } from '../utils.js';
import { normalizePgTypeBase } from '../db.js';

function getTsType(pgType: string, nullable: boolean): string {
  const { base, isArray } = normalizePgTypeBase(pgType);
  let tsType = 'string';
  if (isArray) {
    tsType = 'string[]';
  } else {
    switch (base) {
      case 'integer':
      case 'smallint':
      case 'bigint':
      case 'numeric':
      case 'double precision':
      case 'real':
        tsType = 'number';
        break;
      case 'boolean':
        tsType = 'boolean';
        break;
      case 'jsonb':
        tsType = 'any';
        break;
      default:
        tsType = 'string';
        break;
    }
  }
  return nullable ? `${tsType} | null` : tsType;
}

export function generateType(state: CodegenState): string {
  const typeName = state.dsName; // E.g., Customer
  const fields = state.columns
    .map((col) => {
      const propName = camelCase(col.name);
      const tsType = getTsType(col.type, col.nullable);
      return `  ${propName}: ${tsType};`;
    })
    .join('\n');

  return `/* Generated by uv-core codegen */

export interface ${typeName} {
${fields}
}
`;
}
