import fs from 'node:fs/promises';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import type { CodegenState } from './types.js';
import { generateDs } from './templates/dsTemplate.js';
import { generateType } from './templates/typeTemplate.js';
import { generateStore } from './templates/storeTemplate.js';
import { generateForm } from './templates/formTemplate.js';
import { generatePageContent, generatePage } from './templates/pageTemplate.js';
import { generateTableColumns } from './templates/tableColumnsTemplate.js';
import { generateSmartSearchColumns } from './templates/smartSearchColumnsTemplate.js';

async function writeFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf-8');
}

/**
 * Automatically updates the DS index file for the given module to export the new datasource.
 * Mirrors core's `updateDataSourceIndex` behaviour.
 */
async function updateDataSourceIndex(dsName: string, moduleCode: string, rootDir: string): Promise<void> {
  const indexPath = path.join(
    rootDir,
    'src/lib/server/ds/defs',
    moduleCode ? `${moduleCode}/` : '',
    'index.ts',
  );

  if (!existsSync(indexPath)) {
    // Create a minimal index file if it doesn't exist
    const newContent = `/* Generated by uv-core codegen */\n\nimport { ${dsName}DS } from './${dsName}DS.js';\n\nexport const ${moduleCode ? moduleCode.toUpperCase() : 'DS'}_DATASOURCES = {\n  ${dsName}: ${dsName}DS,\n};\n`;
    await writeFile(indexPath, newContent);
    return;
  }

  const importStatement = `import { ${dsName}DS } from './${dsName}DS.js';`;
  const exportEntry = `  ${dsName}: ${dsName}DS,`;

  let content = readFileSync(indexPath, 'utf8');
  let changed = false;

  if (!content.includes(importStatement)) {
    // Insert import after the last import line or at the top
    const firstExportIdx = content.indexOf('\nexport ');
    if (firstExportIdx !== -1) {
      content = content.slice(0, firstExportIdx) + '\n' + importStatement + content.slice(firstExportIdx);
    } else {
      content = importStatement + '\n' + content;
    }
    changed = true;
  }

  if (!content.includes(exportEntry)) {
    // Insert inside the export object
    const pattern = /export const \w+ = \{\r?\n/;
    content = content.replace(pattern, (match) => `${match}${exportEntry}\n`);
    changed = true;
  }

  if (changed) {
    writeFileSync(indexPath, content);
  }
}

export async function generateFiles(
  state: CodegenState,
): Promise<{ success: boolean; files: string[]; error?: string }> {
  try {
    const writtenFiles: string[] = [];
    const rootDir = process.cwd();

    const { dsName, moduleCode = '', subModuleCode, createPage, template, pageRouteName } = state;

    // 1. Server DataSource  →  src/lib/server/ds/defs/{module}/{dsName}DS.ts
    const dsFileName = `${dsName}DS.ts`;
    const dsPath = path.join(
      rootDir,
      'src/lib/server/ds/defs',
      moduleCode ? moduleCode : '',
      dsFileName,
    );
    await writeFile(dsPath, generateDs(state));
    writtenFiles.push(dsPath);

    // Update the module DS index
    await updateDataSourceIndex(dsName, moduleCode, rootDir);

    // 2. TypeScript Row Type  →  src/lib/common/ds/types/{module}/{dsName}.ts
    const typePath = path.join(
      rootDir,
      'src/lib/common/ds/types',
      moduleCode ? moduleCode : '',
      `${dsName}.ts`,
    );
    await writeFile(typePath, generateType(state));
    writtenFiles.push(typePath);

    // 3–7. Page route files (if createPage is true)
    if (createPage) {
      const routeName = pageRouteName || state.tableName.toLowerCase().replace(/_/g, '-');

      // Build the full page route path (mirrors core's (secure) structure)
      let routeParts = 'src/app';
      if (moduleCode) routeParts += `/${moduleCode}`;
      if (subModuleCode) routeParts += `/${subModuleCode}`;
      routeParts += `/${routeName}`;
      const fullPath = path.join(rootDir, routeParts);

      // 3. hooks/use-store.ts
      const storePath = path.join(fullPath, 'hooks', 'use-store.ts');
      await writeFile(storePath, generateStore(state));
      writtenFiles.push(storePath);

      // 4. hooks/smart-search-columns.ts
      const smartSearchPath = path.join(fullPath, 'hooks', 'smart-search-columns.ts');
      await writeFile(smartSearchPath, generateSmartSearchColumns(state));
      writtenFiles.push(smartSearchPath);

      // 5. hooks/table-columns.tsx
      const tableColumnsPath = path.join(fullPath, 'hooks', 'table-columns.tsx');
      await writeFile(tableColumnsPath, generateTableColumns(state));
      writtenFiles.push(tableColumnsPath);

      // 6. components/edit-form.tsx  (only for page-layout template)
      if (template === 'page-layout') {
        const editFormPath = path.join(fullPath, 'components', 'edit-form.tsx');
        await writeFile(editFormPath, generateForm(state));
        writtenFiles.push(editFormPath);
      }

      // 7. page-content.tsx  +  page.tsx
      const pageContentPath = path.join(fullPath, 'page-content.tsx');
      await writeFile(pageContentPath, generatePageContent(state));
      writtenFiles.push(pageContentPath);

      const pagePath = path.join(fullPath, 'page.tsx');
      await writeFile(pagePath, generatePage(state));
      writtenFiles.push(pagePath);
    }

    return { success: true, files: writtenFiles };
  } catch (error: any) {
    return { success: false, files: [], error: error.message };
  }
}
