/* Generated by uv-core codegen */

import fs from 'node:fs/promises';
import path from 'node:path';
import type { CodegenState } from './types.js';
import { generateDs } from './templates/dsTemplate.js';
import { generateType } from './templates/typeTemplate.js';
import { generateStore } from './templates/storeTemplate.js';
import { generateForm } from './templates/formTemplate.js';
import { generatePage } from './templates/pageTemplate.js';

export async function generateFiles(state: CodegenState): Promise<{ success: boolean; files: string[]; error?: string }> {
  try {
    const writtenFiles: string[] = [];
    const rootDir = process.cwd();

    // 1. Server DataSource
    const dsCode = generateDs(state);
    const dsPath = path.join(rootDir, 'src/lib/server/ds/defs', `${state.dsName}DataSource.ts`);
    await fs.mkdir(path.dirname(dsPath), { recursive: true });
    await fs.writeFile(dsPath, dsCode, 'utf-8');
    writtenFiles.push(dsPath);

    // 2. TypeScript Row Type
    const typeCode = generateType(state);
    const typePath = path.join(rootDir, 'src/lib/common/ds/types', `${state.dsName}.ts`);
    await fs.mkdir(path.dirname(typePath), { recursive: true });
    await fs.writeFile(typePath, typeCode, 'utf-8');
    writtenFiles.push(typePath);

    // 3. Client Valtio Store Hook
    const storeCode = generateStore(state);
    const storePath = path.join(rootDir, 'src/lib/client/hooks', `use${state.dsName}Store.ts`);
    await fs.mkdir(path.dirname(storePath), { recursive: true });
    await fs.writeFile(storePath, storeCode, 'utf-8');
    writtenFiles.push(storePath);

    // 4. Form Component (if template uses editing form)
    if (state.template === 'page-layout') {
      const formCode = generateForm(state);
      const formPath = path.join(rootDir, 'src/components', `${state.dsName}Form.tsx`);
      await fs.mkdir(path.dirname(formPath), { recursive: true });
      await fs.writeFile(formPath, formCode, 'utf-8');
      writtenFiles.push(formPath);
    }

    // 5. React Page (if createPage is true)
    if (state.createPage) {
      const pageCode = generatePage(state);
      const routeName = state.pageRouteName || state.tableName.toLowerCase().replace(/_/g, '-');
      const pagePath = path.join(rootDir, 'src/app', routeName, 'page.tsx');
      await fs.mkdir(path.dirname(pagePath), { recursive: true });
      await fs.writeFile(pagePath, pageCode, 'utf-8');
      writtenFiles.push(pagePath);
    }

    return { success: true, files: writtenFiles };
  } catch (error: any) {
    return { success: false, files: [], error: error.message };
  }
}
